---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Mon app K8s</title>
    </head>
    <body>
      <h1>Hello depuis Kubernetes ! 🚀</h1>
      <p>Cette page est servie par nginx et configurée via un ConfigMap.</p>
    </body>
    </html>
